/*
 * ThumbyDOOM — device entry point.
 *
 * Phase 0: brings up LCD + buttons + audio, draws a boot splash,
 * hands off to D_DoomMain(). Standalone firmware — no FATFS, no
 * USB MSC. The WHD blob is baked into flash as a const array
 * (doom1_whd_data) linked from doom1_whd.c (generated by CMake).
 *
 * RP2350 @ 250 MHz (overclockable to 300 MHz if the renderer needs
 * headroom). Dual core: core0 runs game + renderer, core1 runs the
 * OPL2 mixer feeding the PWM audio ring.
 */
#include <stdio.h>
#include <string.h>

#include "pico/stdlib.h"
#include "pico/stdio/driver.h"
#include "hardware/clocks.h"

#include "doom_lcd_gc9107.h"
#include "doom_buttons.h"
#include "doom_audio_pwm.h"
#include "doom_font.h"

#ifdef THUMBYONE_SLOT_MODE
#include "hardware/structs/qmi.h"
/* When launched via rom_chain_image from ThumbyOne's lobby, the
 * bootrom sets up QMI ATRANS slot 0 to cover DOOM's 2.5 MB
 * partition at physical 0x1A0000. Slots 1..3 are left at SIZE=0,
 * which bus-faults on any access in their windows
 * (0x10400000..0x11000000 logical).
 *
 * DOOM's vendored rp2040-doom code has get_end_of_flash() which
 * walks flash in 2 MB strides from 0x10200000 all the way to
 * 0x11000000 looking for end-of-image. Without the ATRANS
 * extension it hard-faults the moment it reads into slot 1.
 *
 * Map slots 1..3 as identity-ish for the rest of the XIP window
 * so any physical flash address is readable. DOOM's settings
 * save (which is what needs get_end_of_flash's answer) is
 * irrelevant in ThumbyOne mode — settings belong on the shared
 * FAT — but we'd rather let DOOM boot with a nonsense settings
 * address than fault. Step-D (return-to-lobby menu + shared
 * settings) will properly neutralise the save path later. */
__attribute__((constructor(101)))
static void thumbyone_setup_atrans_slots(void) {
    qmi_hw->atrans[1] = (0x400u << 16) | 0x400u;
    qmi_hw->atrans[2] = (0x400u << 16) | 0x800u;
    qmi_hw->atrans[3] = (0x400u << 16) | 0xC00u;
    __asm__ volatile("dsb" ::: "memory");
}
#endif

/* Framebuffer used for boot splash + (later) handed to the Doom
 * renderer as its scanout target. 128x128 RGB565. */
uint16_t g_fb[128 * 128];

static void fb_fill(uint16_t c) {
    for (int i = 0; i < 128 * 128; i++) g_fb[i] = c;
}

/* --- DOS-style boot log ------------------------------------------ */
/* Real init messages are routed here via boot_printf() which Doom's
 * startup code calls through our __wrap_printf. Lines scroll up
 * when the screen fills. Header bar stays pinned at top. */

#define DOS_WHITE  0xB596   /* DOS light grey */
#define DOS_RED_BG 0xA800   /* dark red header */
#define BOOT_LINE_H  7
#define BOOT_TOP      10     /* first text line y (below header) */
#define BOOT_MAX_Y    (128 - BOOT_LINE_H)

static int  boot_y = BOOT_TOP;
int  boot_active = 1;    /* cleared once D_DoomMain reaches game loop */

void boot_printf(const char *text)
{
    if (!boot_active) return;

    /* Scroll if we've hit the bottom. */
    if (boot_y > BOOT_MAX_Y) {
        /* Shift framebuffer up by one line height. */
        int header_px = BOOT_TOP * 128;
        int shift = BOOT_LINE_H * 128;
        int body = 128 * 128 - header_px - shift;
        for (int i = 0; i < body; i++)
            g_fb[header_px + i] = g_fb[header_px + shift + i];
        /* Clear the new bottom line. */
        for (int i = header_px + body; i < 128 * 128; i++)
            g_fb[i] = 0x0000;
        boot_y = BOOT_MAX_Y;
    }

    doom_font_draw(g_fb, text, 2, boot_y, DOS_WHITE);
    boot_y += BOOT_LINE_H;
    doom_lcd_present(g_fb);
    doom_lcd_wait_idle();
    sleep_ms(50);
}

static void boot_splash(void) {
    fb_fill(0x0000);

    /* Red header bar — pinned at top. */
    for (int py = 0; py < 8; py++)
        for (int px = 0; px < 128; px++)
            g_fb[py * 128 + px] = DOS_RED_BG;
    doom_font_draw(g_fb, "ThumbyDOOM v1.0", 2, 1, 0xFFFF);
    doom_lcd_present(g_fb);
    doom_lcd_wait_idle();
}

/* --- Boot log capture --------------------------------------------- */
/* Doom's DEH_printf → printf → pico_stdio → putchar_raw. We
 * accumulate characters into a line buffer and flush to the LCD
 * on newline. Called from boot_putchar installed as a stdio driver. */

static char  boot_linebuf[48];
static int   boot_linepos;

static void boot_stdio_out(const char *buf, int len) {
    if (!boot_active) return;
    for (int i = 0; i < len; i++) {
        char c = buf[i];
        if (c == '\n' || boot_linepos >= (int)sizeof(boot_linebuf) - 1) {
            boot_linebuf[boot_linepos] = 0;
            if (boot_linepos > 0) boot_printf(boot_linebuf);
            boot_linepos = 0;
        } else if (c >= ' ') {
            boot_linebuf[boot_linepos++] = c;
        }
    }
}

static stdio_driver_t boot_stdio_driver = {
    .out_chars = boot_stdio_out,
    .in_chars  = NULL,
#if PICO_STDIO_ENABLE_CRLF_SUPPORT
    .crlf_enabled = false,
#endif
};

/* --- Hex formatting helper ---------------------------------------- */
static const char hex_digits[] = "0123456789ABCDEF";
static void hex_str(char *buf, const char *label, uint32_t val) {
    int i = 0;
    while (*label) buf[i++] = *label++;
    for (int j = 0; j < 8; j++)
        buf[i++] = hex_digits[(val >> (28 - j * 4)) & 0xF];
    buf[i] = 0;
}

/* --- DWT hardware data watchpoint --------------------------------- */
/* Cortex-M33 has 4 DWT comparators. We use comparator 0 to watch
 * for writes to a 4-byte region containing a thinker's function and
 * pool_info (offset 4-7). When the write fires, DebugMonitor_Handler
 * captures the faulting PC — telling us exactly which instruction
 * corrupts the thinker header. */

/* DWT and CoreDebug registers — direct addresses to avoid CMSIS
 * header dependency issues with the Pico SDK. */
#define DWT_CTRL     (*(volatile uint32_t *)0xE0001000)
#define DWT_COMP0    (*(volatile uint32_t *)0xE0001020)
#define DWT_MASK0    (*(volatile uint32_t *)0xE0001024)
#define DWT_FUNC0    (*(volatile uint32_t *)0xE0001028)
#define DEMCR        (*(volatile uint32_t *)0xE000EDFC)
#define DEMCR_TRCENA (1 << 24)
#define DEMCR_MON_EN (1 << 16)

static volatile uint32_t dwt_watch_addr;

void thumby_dwt_watch(void *thinker_addr)
{
    /* Watch the word at thinker+4 (contains function + pool_info). */
    uint32_t addr = (uint32_t)(uintptr_t)thinker_addr + 4;
    dwt_watch_addr = addr;

    /* Enable DWT trace and DebugMonitor exception. */
    DEMCR |= DEMCR_TRCENA | DEMCR_MON_EN;

    /* Comparator 0: data write watchpoint, 4-byte aligned match.
     * FUNCTION bits: [27:24]=MATCH=0110 (write), [4]=ACTION=1 (debug event) */
    DWT_COMP0 = addr;
    DWT_MASK0 = 0;        /* exact match on 4-byte aligned word */
    DWT_FUNC0 = (0x6 << 24) | (1 << 4);
}

void __attribute__((naked)) isr_debug_monitor(void) {
    __asm volatile(
        "tst   lr, #4          \n"
        "ite   eq               \n"
        "mrseq r0, msp          \n"
        "mrsne r0, psp          \n"
        "ldr   r1, [r0, #20]   \n"  /* stacked LR */
        "ldr   r0, [r0, #24]   \n"  /* stacked PC */
        "b     dwt_fault        \n"
    );
}

void __attribute__((used)) dwt_fault(uint32_t pc, uint32_t lr) {
    /* Disable the watchpoint so we don't re-trigger. */
    DWT_FUNC0 = 0;

    doom_lcd_wait_idle();
    fb_fill(0x07E0);  /* green background — distinct from red/blue */

    doom_font_draw_2x(g_fb, "WATCHPOINT", 4, 2, 0x0000);

    char buf[24];
    hex_str(buf, "PC :", pc);
    doom_font_draw_2x(g_fb, buf, 4, 22, 0x0000);
    hex_str(buf, "LR :", lr);
    doom_font_draw_2x(g_fb, buf, 4, 38, 0x0000);
    hex_str(buf, "ADR:", dwt_watch_addr);
    doom_font_draw_2x(g_fb, buf, 4, 54, 0x0000);

    doom_font_draw(g_fb, "look up PC in .dis", 4, 76, 0x0000);

    doom_lcd_present(g_fb);
    doom_lcd_wait_idle();
    for (;;) __asm volatile("wfi");
}

/* --- HardFault handler -------------------------------------------- */
/* Cortex-M33 pushes {R0,R1,R2,R3,R12,LR,PC,xPSR} on fault.
 * We grab the faulting PC and paint it on the LCD so we can look
 * it up in the .dis file without needing a debugger attached. */

void __attribute__((used)) fault_screen(uint32_t pc, uint32_t lr) {
    /* Bypass DMA — write SPI blocking so we don't depend on any
     * state that may be corrupted. */
    doom_lcd_wait_idle();

    fb_fill(0xF800);  /* red background */

    doom_font_draw_2x(g_fb, "HARDFAULT", 8, 4, 0xFFFF);

    /* Print PC and LR as hex strings */
    char buf[20];

    static const char hex[] = "0123456789ABCDEF";
    buf[0] = 'P'; buf[1] = 'C'; buf[2] = ':';
    for (int i = 0; i < 8; i++)
        buf[3 + i] = hex[(pc >> (28 - i * 4)) & 0xF];
    buf[11] = 0;
    doom_font_draw_2x(g_fb, buf, 4, 28, 0xFFFF);

    buf[0] = 'L'; buf[1] = 'R'; buf[2] = ':';
    for (int i = 0; i < 8; i++)
        buf[3 + i] = hex[(lr >> (28 - i * 4)) & 0xF];
    buf[11] = 0;
    doom_font_draw_2x(g_fb, buf, 4, 48, 0xFFFF);

    doom_font_draw(g_fb, "look up PC in .dis", 4, 72, 0xFFE0);

    doom_lcd_present(g_fb);
    doom_lcd_wait_idle();
    for (;;) __asm volatile("wfi");
}

/* Naked so we can read the exception stack frame correctly.
 * On entry, the hardware has selected MSP or PSP; we test bit 2
 * of LR (EXC_RETURN) to determine which. */
void __attribute__((naked)) isr_hardfault(void) {
    __asm volatile(
        "tst   lr, #4          \n"  /* test EXC_RETURN bit 2 */
        "ite   eq               \n"
        "mrseq r0, msp          \n"  /* fault used MSP */
        "mrsne r0, psp          \n"  /* fault used PSP */
        "ldr   r1, [r0, #20]   \n"  /* r1 = stacked LR  (offset 20) */
        "ldr   r0, [r0, #24]   \n"  /* r0 = stacked PC  (offset 24) */
        "b     fault_screen     \n"
    );
}

/* --- Generic diagnostic crash screen ------------------------------ */
/* Callable from anywhere to display up to 4 labelled hex values
 * on a blue screen and halt. Used by validation traps. */

void __attribute__((used)) thumby_crash(
    const char *title,
    uint32_t v0, uint32_t v1, uint32_t v2, uint32_t v3)
{
    doom_lcd_wait_idle();
    fb_fill(0x0010);  /* dark blue background */
    char buf[24];

    doom_font_draw_2x(g_fb, title, 4, 2, 0xF800);

    hex_str(buf, "THK:", v0);
    doom_font_draw_2x(g_fb, buf, 4, 22, 0xFFFF);
    hex_str(buf, "PI :", v1);
    doom_font_draw_2x(g_fb, buf, 4, 38, 0xFFFF);
    hex_str(buf, "BLK:", v2);
    doom_font_draw_2x(g_fb, buf, 4, 54, 0xFFFF);
    hex_str(buf, "SZ :", v3);
    doom_font_draw_2x(g_fb, buf, 4, 70, 0xFFFF);

    doom_lcd_present(g_fb);
    doom_lcd_wait_idle();
    for (;;) __asm volatile("wfi");
}

/* Forward decl — provided by port/i_main_thumby.c which in turn
 * calls Doom's D_DoomMain(). */
extern void thumby_doom_main(void);

int main(void) {
    /* Overclock to 250 MHz; Doom renderer is the hot path. We can
     * push to 300 MHz later if profiling says we need it. */
    set_sys_clock_khz(250000, true);

    stdio_init_all();
    stdio_set_driver_enabled(&boot_stdio_driver, true);

    doom_lcd_init();
    doom_buttons_init();
    doom_audio_pwm_init();

    boot_splash();

    thumby_doom_main();

    /* Should never return. Flash the screen red if it does. */
    while (1) {
        fb_fill(0xF800);
        doom_lcd_present(g_fb);
        doom_lcd_wait_idle();
        sleep_ms(200);
        fb_fill(0x0000);
        doom_lcd_present(g_fb);
        doom_lcd_wait_idle();
        sleep_ms(200);
    }
}
