/*
 * ThumbyDOOM — device entry point.
 *
 * Phase 0: brings up LCD + buttons + audio, draws a boot splash,
 * hands off to D_DoomMain(). Standalone firmware — no FATFS, no
 * USB MSC. The WHD blob is baked into flash as a const array
 * (doom1_whd_data) linked from doom1_whd.c (generated by CMake).
 *
 * RP2350 @ 250 MHz (overclockable to 300 MHz if the renderer needs
 * headroom). Dual core: core0 runs game + renderer, core1 runs the
 * OPL2 mixer feeding the PWM audio ring.
 */
#include <stdio.h>
#include <string.h>

#include "pico/stdlib.h"
#include "hardware/clocks.h"

#include "doom_lcd_gc9107.h"
#include "doom_buttons.h"
#include "doom_audio_pwm.h"
#include "doom_font.h"

/* Framebuffer used for boot splash + (later) handed to the Doom
 * renderer as its scanout target. 128x128 RGB565. */
uint16_t g_fb[128 * 128];

static void fb_fill(uint16_t c) {
    for (int i = 0; i < 128 * 128; i++) g_fb[i] = c;
}

static void boot_splash(void) {
    fb_fill(0x0000);
    doom_font_draw(g_fb, "ThumbyDOOM",  24, 40, 0xF800); /* red */
    doom_font_draw(g_fb, "v0.1",        48, 52, 0xFFFF);
    doom_font_draw(g_fb, "shareware",   32, 72, 0xC618);
    doom_font_draw(g_fb, "GPLv2",       44, 100, 0x4208);
    doom_lcd_present(g_fb);
    doom_lcd_wait_idle();
    sleep_ms(1200);
}

/* Forward decl — provided by port/i_main_thumby.c which in turn
 * calls Doom's D_DoomMain(). */
extern void thumby_doom_main(void);

int main(void) {
    /* Overclock to 250 MHz; Doom renderer is the hot path. We can
     * push to 300 MHz later if profiling says we need it. */
    set_sys_clock_khz(250000, true);

    stdio_init_all();

    doom_lcd_init();
    doom_buttons_init();
    doom_audio_pwm_init();

    boot_splash();

    thumby_doom_main();

    /* Should never return. Flash the screen red if it does. */
    while (1) {
        fb_fill(0xF800);
        doom_lcd_present(g_fb);
        doom_lcd_wait_idle();
        sleep_ms(200);
        fb_fill(0x0000);
        doom_lcd_present(g_fb);
        doom_lcd_wait_idle();
        sleep_ms(200);
    }
}
